pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
    }
}

rootProject.name = "md-page-harvester"

include(
    "apps:service",
    "modules:cqrs",
    "modules:catalog",
    "modules:downloader",
    "modules:storage",
    "modules:scheduler",
    "modules:api"
)
